### ISSUE TITLE
It doesn't work out of the box.

### ISSUE THREAD

**Issue by trusktr** [xolvio/md-blog#37]
I tried following the setup instructions. I did (1) added the templates and (2) added the `Roles.addUsersToRoles(user._id, ['mdblog-author']);` line, and I get error like this when I try to run `meteor`:

```
W20150607-13:32:04.766(-7)? (STDERR)
W20150607-13:32:04.766(-7)? (STDERR) /Users/josephpea/.meteor/packages/meteor-tool/.1.1.3.egxex7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150607-13:32:04.766(-7)? (STDERR)                                            throw(ex);
W20150607-13:32:04.766(-7)? (STDERR)                                                  ^
W20150607-13:32:04.771(-7)? (STDERR) Error: --settings or METEOR_SETTINGS required.
W20150607-13:32:04.771(-7)? (STDERR)     at Object._.extend.setDefaults (packages/ogourment:settings/settings.js:23:1)
W20150607-13:32:04.771(-7)? (STDERR)     at _ (packages/xolvio:md-blog/server/blog-server.js:5:1)
W20150607-13:32:04.771(-7)? (STDERR)     at _ (packages/xolvio:md-blog/server/blog-server.js:123:1)
W20150607-13:32:04.771(-7)? (STDERR)     at /Users/josephpea/test/meteor-blog-test/.meteor/local/build/programs/server/packages/xolvio_md-blog.js:267:4
W20150607-13:32:04.771(-7)? (STDERR)     at /Users/josephpea/test/meteor-blog-test/.meteor/local/build/programs/server/packages/xolvio_md-blog.js:339:3
W20150607-13:32:04.771(-7)? (STDERR)     at /Users/josephpea/test/meteor-blog-test/.meteor/local/build/programs/server/boot.js:222:10
W20150607-13:32:04.771(-7)? (STDERR)     at Array.forEach (native)
W20150607-13:32:04.772(-7)? (STDERR)     at Function._.each._.forEach (/Users/josephpea/.meteor/packages/meteor-tool/.1.1.3.egxex7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150607-13:32:04.772(-7)? (STDERR)     at /Users/josephpea/test/meteor-blog-test/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

**Comment by samhatoum** [comment]
This is expected behavior (though it should probably be in the docs!) you have to start meteor with a settings file. See this on for an example: https://github.com/xolvio/md-blog/blob/master/app/settings.json

**Comment by trusktr** [comment]
I tried that too, but I still get the same error. I copied the example from the readme

```js
{
  "public": {
    "blog": {
      "name": "The Xolv.io md-blog",
      "Description": "Get verbal on your websites.",
      "prettify": {
        "syntax-highlighting": true,
        "element-classes": [
          {
            "locator": "img",
            "classes": ["pure-img"]
          },
          {
            "locator": "button",
            "classes": ["pure-button"]
          }
        ]
      },
      "sortBy": {"date": -1},
      "blogPath": "/blog",
      "archivePath": "/blog/archive",
      "useUniqueBlogPostsPath": true
    }
  }
}
```

and pasted it into `settings.json`, so my app folder looks like this:

```
 ❯ tree -a                                                                                                                                                                                       [18:49:33]
.
├── .meteor
│·· ├── .finished-upgraders
│·· ├── .gitignore
│·· ├── .id
│·· ├── local
│·· │·· └── isopacks
│·· ├── packages
│·· ├── platforms
│·· ├── release
│·· └── versions
├── meteor-blog-test.css
├── meteor-blog-test.html
├── meteor-blog-test.js
└── settings.json
```

**Comment by samhatoum** [comment]
and just checking, are you starting meteor like this:

`meteor --settings settings.json` ?

**Comment by trusktr** [comment]
`meteor-blog-test.html` looks like this:

```html
<head>
  <title>meteor-blog-test</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="blogListLayout">
  {{> yield}}
</template>

<template name="blogPostLayout">
  {{> yield}}
</template>
```

and `meteor-blog-test.js` looks like this:

```js
if (Meteor.isClient) {
Roles.addUsersToRoles(user._id, ['mdblog-author']);
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
```

**Comment by trusktr** [comment]
oh, no, I didn't start meteor like that! xD

**Comment by trusktr** [comment]
Now that I'm logged in, I don't see any way to edit the blog. I've added `Roles.addUsersToRoles(user._id, ['mdblog-author']);` to my client code. Do I need to do something else?

**Comment by samhatoum** [comment]
do you see a new blog post button?

If so, the way you edit is by going into a blog post, and then clicking on the area you want to edit

**Comment by trusktr** [comment]
@samhatoum I see this:

![screen shot 2015-06-07 at 7 05 07 pm](https://cloud.githubusercontent.com/assets/297678/8027219/26fcecfe-0d48-11e5-8e33-f5e09aa9a773.png)

and this once I've clicked on the post:

![screen shot 2015-06-07 at 7 05 44 pm](https://cloud.githubusercontent.com/assets/297678/8027224/3c3d3696-0d48-11e5-8ab0-bbeea988d5ef.png)

**Comment by samhatoum** [comment]
`Roles.addUsersToRoles(user._id, ['mdblog-author']);` needs to happen on the server I think

**Comment by trusktr** [comment]
@samhatoum It says `Roles` is undefined on the server side. hehe. Let me go learn about alanning:roles...

**Comment by trusktr** [comment]
Cool, yeah, adding the role manually in mongodb worked.

**Comment by samhatoum** [comment]
awesome, enjoy :)

**Comment by trusktr** [comment]
Thanks. (:
